name: 'AI Issue Generator'
description: 'Automatically creates GitHub issues from Pull Requests using AI'
author: 'barabum0'
branding:
  icon: 'file-text'
  color: 'purple'

inputs:
  openai_api_key:
    description: 'OpenAI API key for generating issue content'
    required: true
  github_token:
    description: 'GitHub token for API access (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}

outputs:
  issue_number:
    description: 'The number of the created issue'
  issue_url:
    description: 'The URL of the created issue'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}